os: linux
dist: xenial
language: node_js
node_js:
  - '10'

before_install:
  - npm install netlify-cli -g

script:
  - yarn install
  - yarn build

deploy:
  - provider: script
    script: netlify deploy --dir=public
    on:
      all_branches: true
  - provider: script
    script: netlify deploy --dir=public --prod
    on:
      branch: master

cache: 
  directories:
    - node_modules
    - .cache
    - public
    - $(npm config get prefix)/bin/netlify
