os: linux
dist: xenial
language: node_js
node_js:
  - '10'

before_install:
  - npm install netlify-cli -g

script:
  - yarn install
  - yarn build

deploy:
  - provider: script
    script: 'netlify deploy --dir=public --functions=functions --message="$TRAVIS_COMMIT: $TRAVIS_COMMIT_MESSAGE"'
    skip_cleanup: true
    on:
      all_branches: true
  - provider: script
    script: 'netlify deploy --dir=public  --functions=functions --prod --message="$TRAVIS_COMMIT: $TRAVIS_COMMIT_MESSAGE"'
    skip_cleanup: true
    on:
      branch: master

cache:
  directories:
    - node_modules
    - .cache
    - public
    - $(npm config get prefix)/bin/netlify
